services:
  backend:
    container_name: task-manager-backend
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./backend:/app
    command:
      [
        'uvicorn',
        'app.main:app',
        '--host',
        '0.0.0.0',
        '--port',
        '8000',
        '--reload',
      ]

  frontend:
    container_name: task-manager-frontend
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ['npm', 'run', 'dev']

  db:
    container_name: task-manager-db
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
