services:
  db:
    container_name: task-manager-db
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "taskdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    container_name: task-manager-backend
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    working_dir: /app
    volumes:
      - ./backend:/app
    command:
      [ 
        "sh", "-c", "wait-for-it db:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
      ]

  frontend:
    container_name: task-manager-frontend
    platform: linux/amd64
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: ['npm', 'run', 'dev']

volumes:
  db_data:
  node_modules: